Repository Tave-Makers/SURF-FE, pull requests merged in 2025-10, with the labels that each got.

#86 [HOTFIX] 배포 에러 backPath 추가
  src/shared/config/routes.tsx
Labels: 진주 💎, 🚨HOTFIX

#90 [HOTFIX] 온보딩레이아웃에 use client 추가
  src/app-pages/onboarding/ui/OnBoardingPage.tsx
  src/widgets/onboarding/ui/OnBoardingLayout.tsx
Labels: 다희 ☀️, 🚨HOTFIX

#95 [HOTFIX] header route config를 factory 함수로 변경하여 router 동작 지원
  src/shared/config/routes.tsx
  src/widgets/header/ui/AppHeader.tsx
  src/widgets/navigation/ui/AppNavigation.tsx
Labels: 진주 💎, 🚨HOTFIX

#69 [FEAT] 활동점수 페이지 구현
  src/app-pages/activity-score/ui/ActivityScorePage.tsx
  src/entities/activity-score/model/adapter.ts
  src/entities/activity-score/model/meta.ts
  src/entities/activity-score/model/types.ts
  src/entities/activity-score/ui/ActivityHistoryItem.tsx
  src/entities/activity-score/ui/ActivityHistoryList.tsx
  src/entities/activity-score/ui/ActivitySummaryItem.tsx
  src/entities/activity-score/ui/ActivitySummaryTooltip.tsx
  src/widgets/activity-score/ActivityScoreCard.tsx
Labels: ✨ FEAT, 진주 💎

#88 [REFACTOR] Alert 컴포넌트 prop 추가 및 Alert 스토리북 개선
  src/shared/ui/alert/Alert.stories.tsx
  src/shared/ui/alert/Alert.tsx
Labels: ♻️ REFACTOR, 서연 🍀

#102 [FEAT] 설정->이용약관 페이지 구현
  app/(sub)/mypage/settings/policy/marketing-info/page.tsx
  app/(sub)/mypage/settings/policy/personal-info-policy/page.tsx
  app/(sub)/mypage/settings/policy/personal-info/page.tsx
  app/(sub)/mypage/settings/policy/service/page.tsx
  package.json
  pnpm-lock.yaml
  src/app-pages/mypage/settings/policy/ui/MarketingPolicyPage.tsx
  src/app-pages/mypage/settings/policy/ui/PersonalInfoPolicyPage.tsx
  src/app-pages/mypage/settings/policy/ui/PolicyPage.tsx
  src/app-pages/mypage/settings/policy/ui/ServicePolicyPage.tsx
  src/entities/policy/model/constants.ts
  src/entities/policy/model/preprocessMarkdown.ts
  src/entities/policy/model/types.ts
  src/entities/policy/ui/Markdown.tsx
  src/entities/policy/ui/PolicyDetailItem.tsx
  src/entities/policy/ui/PolicyItem.tsx
Labels: ✨ FEAT, 서연 🍀

#106 [REFACTOR] 활동점수 페이지 스크롤 영역 변경
  app/(main)/layout.tsx
  app/(sub)/layout.tsx
  src/app-pages/activity-score/ui/ActivityScorePage.tsx
  src/app-pages/bylaws/ui/BylawsPage.tsx
Labels: ♻️ REFACTOR, 진주 💎

#111 [REFACTOR] 도메인별 트래킹 함수 생성용 팩토리 함수 제작
  src/features/auth/lib/trackAuthEvent.ts
  src/shared/lib/createDomainTracker.ts
Labels: ♻️ REFACTOR, 진주 💎
