Repository Tave-Makers/SURF-FE, pull requests merged in 2025-09, with the labels that each got.

#13 [CHORE] 이슈/PR 템플릿 업데이트
  .github/ISSUE_TEMPLATE/surf-fe-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🧺 CHORE, 💎 진주

#34 [CHORE(eslint)] scripts 디렉토리 any 규칙 완화로 lint 에러 해결
  eslint.config.js
Labels: 🧺 CHORE, 💎 진주

#36 [FEAT] Alert 공통 컴포넌트 구현
  src/shared/ui/alert/Alert.stories.tsx
  src/shared/ui/alert/Alert.tsx
  src/shared/ui/solid-button/SolidButton.stories.tsx
  src/shared/ui/solid-button/SolidButton.tsx
  src/shared/ui/text-button/TextButton.stories.tsx
  src/shared/ui/text-button/TextButton.tsx
Labels: ✨ FEAT, 🍀 서연

#37 [FEAT] CheckList, Sheet 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/shared/styles/globals.css
  src/shared/ui/check-list/CheckList.stories.tsx
  src/shared/ui/check-list/CheckList.tsx
  src/shared/ui/sheet/Sheet.stories.tsx
  src/shared/ui/sheet/Sheet.tsx
Labels: ✨ FEAT, ☀️ 다희

#38 [FEAT] BottomNavigation 컴포넌트 구현
  src/shared/ui/bottom-navigation/BottomNavigation.stories.tsx
  src/shared/ui/bottom-navigation/BottomNavigation.tsx
Labels: ✨ FEAT, ☀️ 다희

#65 [FEAT] 폴더구조 확정 및 레이아웃 기반 라우팅 구성
  app/(main)/chat/page.tsx
  app/(main)/home/page.tsx
  app/(main)/layout.tsx
  app/(main)/mypage/page.tsx
  app/(sub)/layout.tsx
  app/(sub)/onboarding/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  app/signup/page.tsx
  src/app-pages/chat/ui/ChatPage.tsx
  src/app-pages/login/ui/LoginPage.tsx
  src/app-pages/mypage/ui/MyPage.tsx
  src/app-pages/onboarding/ui/OnBoardingPage.tsx
  src/app-pages/signup/ui/SignUpPage.tsx
  src/shared/config/routes.tsx
  src/shared/ui/bottom-navigation/BottomNavigation.tsx
  src/shared/ui/header/Header.tsx
  src/shared/ui/logo/DummyLogo.tsx
  src/shared/ui/text-input/TextInput.tsx
  src/widgets/header/ui/AppHeader.tsx
  src/widgets/navigation/ui/AppNavigation.tsx
Labels: ✨ FEAT, 다희 ☀️

#67 [FEAT] 카카오로그인 구현
  app/(main)/layout.tsx
  app/(sub)/layout.tsx
  app/login/callback/page.tsx
  app/page.tsx
  package.json
  pnpm-lock.yaml
  src/app-pages/login/ui/KakaoCallBackPage.tsx
  src/app-pages/login/ui/LoginPage.tsx
  src/app/providers/AuthProvider.tsx
  src/features/auth/api/auth-store.ts
  src/features/auth/api/getKakaoLoginCallback.ts
  src/features/auth/api/getValidStatus.ts
  src/features/auth/api/types.ts
  src/features/auth/lib/kakaoLogin.ts
  src/features/auth/model/authLogic.ts
  src/features/auth/model/types.ts
  src/features/auth/model/useAuth.ts
  src/features/auth/model/useAuthHydrated.ts
  src/features/auth/model/useAuthStore.ts
  src/features/auth/ui/KakaoLoginButton.tsx
  src/features/auth/ui/LoginButton.tsx
  src/shared/config/env.ts
  src/shared/config/routes.tsx
  src/shared/lib/axiosInstance.ts
  src/shared/lib/handleApiError.ts
  src/widgets/header/ui/AppHeader.tsx
  src/widgets/navigation/ui/AppNavigation.tsx
Labels: ✨ FEAT, 다희 ☀️

#45 [FEAT] 셀렉트필드 컴포넌트 제작
  src/shared/ui/select-field/SelectField.stories.tsx
  src/shared/ui/select-field/SelectField.tsx
Labels: ✨ FEAT, 지연 🌸

#46 [FEAT] 활동뱃지 컴포넌트 제작
  public/icons/default-circle.svg
  src/shared/assets/icons/profile/default-circle.svg
  src/shared/ui/activity-badge/ActivityBadge.stories.tsx
  src/shared/ui/activity-badge/ActivityBadge.tsx
Labels: ✨ FEAT, 지연 🌸

#58 [FEAT] 탭 컴포넌트 제작
  app/layout.tsx
  src/shared/styles/font-tokens.css
  src/shared/styles/globals.css
  src/shared/ui/tab/Tab.stories.tsx
  src/shared/ui/tab/Tab.tsx
  tokens/typography.json
Labels: ✨ FEAT, 지연 🌸

#70 [REFACTOR] Header 텍스트 버튼 영역을 TextButton 컴포넌트로 교체
  src/shared/ui/header/Header.stories.tsx
  src/shared/ui/header/Header.tsx
  src/shared/ui/text-button/TextButton.tsx
Labels: ♻️ REFACTOR, 다희 ☀️

#75 [CHORE] .coderabbit.yaml 업데이트
  .coderabbit.yaml
Labels: 🧹 CHORE, 지연 🌸
